export const TEAMS = [
	{ id: "mexico", name: "Mexico", group: "A", half: "Left", tier: "Top Tier", flag: "🇲🇽" },
	{ id: "south-africa", name: "South Africa", group: "A", half: "Left", tier: "Underdog", flag: "🇿🇦" },
	{ id: "south-korea", name: "South Korea", group: "A", half: "Left", tier: "Mid Tier", flag: "🇰🇷" },
	{ id: "czechia", name: "Czechia", group: "A", half: "Left", tier: "Mid Tier", flag: "🇨🇿" },
	{ id: "switzerland", name: "Switzerland", group: "B", half: "Left", tier: "Mid Tier", flag: "🇨🇭" },
	{ id: "canada", name: "Canada", group: "B", half: "Left", tier: "Mid Tier", flag: "🇨🇦" },
	{ id: "qatar", name: "Qatar", group: "B", half: "Left", tier: "Underdog", flag: "🇶🇦" },
	{
		id: "bosnia-and-herzegovina",
		name: "Bosnia and Herzegovina",
		group: "B",
		half: "Left",
		tier: "Mid Tier",
		flag: "🇧🇦",
	},
	{ id: "brazil", name: "Brazil", group: "C", half: "Left", tier: "Top Tier", flag: "🇧🇷" },
	{ id: "scotland", name: "Scotland", group: "C", half: "Left", tier: "Mid Tier", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
	{ id: "haiti", name: "Haiti", group: "C", half: "Left", tier: "Underdog", flag: "🇭🇹" },
	{ id: "morocco", name: "Morocco", group: "C", half: "Left", tier: "Top Tier", flag: "🇲🇦" },
	{ id: "united-states", name: "United States", group: "D", half: "Left", tier: "Top Tier", flag: "🇺🇸" },
	{ id: "turkiye", name: "Türkiye", group: "D", half: "Left", tier: "Mid Tier", flag: "🇹🇷" },
	{ id: "australia", name: "Australia", group: "D", half: "Left", tier: "Mid Tier", flag: "🇦🇺" },
	{ id: "paraguay", name: "Paraguay", group: "D", half: "Left", tier: "Mid Tier", flag: "🇵🇾" },
	{ id: "germany", name: "Germany", group: "E", half: "Left", tier: "Top Tier", flag: "🇩🇪" },
	{ id: "ivory-coast", name: "Ivory Coast", group: "E", half: "Left", tier: "Mid Tier", flag: "🇨🇮" },
	{ id: "curacao", name: "Curaçao", group: "E", half: "Left", tier: "Underdog", flag: "🇨🇼" },
	{ id: "ecuador", name: "Ecuador", group: "E", half: "Left", tier: "Mid Tier", flag: "🇪🇨" },
	{ id: "netherlands", name: "Netherlands", group: "F", half: "Left", tier: "Top Tier", flag: "🇳🇱" },
	{ id: "tunisia", name: "Tunisia", group: "F", half: "Left", tier: "Mid Tier", flag: "🇹🇳" },
	{ id: "japan", name: "Japan", group: "F", half: "Left", tier: "Mid Tier", flag: "🇯🇵" },
	{ id: "sweden", name: "Sweden", group: "F", half: "Left", tier: "Mid Tier", flag: "🇸🇪" },
	{ id: "belgium", name: "Belgium", group: "G", half: "Right", tier: "Top Tier", flag: "🇧🇪" },
	{ id: "egypt", name: "Egypt", group: "G", half: "Right", tier: "Mid Tier", flag: "🇪🇬" },
	{ id: "iran", name: "Iran", group: "G", half: "Right", tier: "Mid Tier", flag: "🇮🇷" },
	{ id: "new-zealand", name: "New Zealand", group: "G", half: "Right", tier: "Underdog", flag: "🇳🇿" },
	{ id: "spain", name: "Spain", group: "H", half: "Right", tier: "Top Tier", flag: "🇪🇸" },
	{ id: "uruguay", name: "Uruguay", group: "H", half: "Right", tier: "Top Tier", flag: "🇺🇾" },
	{ id: "saudi-arabia", name: "Saudi Arabia", group: "H", half: "Right", tier: "Underdog", flag: "🇸🇦" },
	{ id: "cape-verde", name: "Cape Verde", group: "H", half: "Right", tier: "Underdog", flag: "🇨🇻" },
	{ id: "france", name: "France", group: "I", half: "Right", tier: "Top Tier", flag: "🇫🇷" },
	{ id: "norway", name: "Norway", group: "I", half: "Right", tier: "Mid Tier", flag: "🇳🇴" },
	{ id: "senegal", name: "Senegal", group: "I", half: "Right", tier: "Mid Tier", flag: "🇸🇳" },
	{ id: "iraq", name: "Iraq", group: "I", half: "Right", tier: "Underdog", flag: "🇮🇶" },
	{ id: "argentina", name: "Argentina", group: "J", half: "Right", tier: "Top Tier", flag: "🇦🇷" },
	{ id: "algeria", name: "Algeria", group: "J", half: "Right", tier: "Mid Tier", flag: "🇩🇿" },
	{ id: "austria", name: "Austria", group: "J", half: "Right", tier: "Mid Tier", flag: "🇦🇹" },
	{ id: "jordan", name: "Jordan", group: "J", half: "Right", tier: "Underdog", flag: "🇯🇴" },
	{ id: "portugal", name: "Portugal", group: "K", half: "Right", tier: "Top Tier", flag: "🇵🇹" },
	{ id: "colombia", name: "Colombia", group: "K", half: "Right", tier: "Mid Tier", flag: "🇨🇴" },
	{ id: "dr-congo", name: "DR Congo", group: "K", half: "Right", tier: "Underdog", flag: "🇨🇩" },
	{ id: "uzbekistan", name: "Uzbekistan", group: "K", half: "Right", tier: "Underdog", flag: "🇺🇿" },
	{ id: "croatia", name: "Croatia", group: "L", half: "Right", tier: "Top Tier", flag: "🇭🇷" },
	{ id: "england", name: "England", group: "L", half: "Right", tier: "Top Tier", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
	{ id: "ghana", name: "Ghana", group: "L", half: "Right", tier: "Mid Tier", flag: "🇬🇭" },
	{ id: "panama", name: "Panama", group: "L", half: "Right", tier: "Underdog", flag: "🇵🇦" },
];
